recaptcha_defaults: &recaptcha_defaults
  PUBLIC_KEY: '6LebKwcTAAAAABKlBEAJdRaocUb4v46KMG7OyfhR'
  PRIVATE_KEY: '6LebKwcTAAAAAKzy3FFAV8lo_Bx8w8ZGNzN_UfCY'

facebook_defaults: &facebook_defaults
  SCOPE: 'user_friends,email,user_location'
  LOGO_URL: /assets/main-logo-dash.png

google_defaults: &google_defaults
  KEY: '18950285410-066kiriporohq1c426q4hdhldqrbohvu.apps.googleusercontent.com'
  SECRET: 'vD_9BiLj-oD7WlHR47IBy6Cw'
  ACCESS_TYPE: 'offline'
  SCOPE: 'https://www.googleapis.com/auth/calendar'
  REDIRECT_URI: '/auth/google_oauth2/callback'

development:
  BASEURL: 'http://staging.twonoo.com:8080'
  FACEBOOK:
    KEY: '1524267501137363'
    SECRET: '6f6e76f615fcf6c4a552cce0f51e71c4'
    <<: *facebook_defaults
  GOOGLE:
    <<: *google_defaults
  MANDRILL:
    APIKEY: 'FkIb4ZNcFM9oEkj7OmjYiQ'
  WEBSOCKET:
    USE_SSL: 'false'
  RECAPTCHA:
    <<: *recaptcha_defaults

production:
  BASEURL: 'https://www.twonoo.com'
  FACEBOOK:
    KEY: '1524267501137363'
    SECRET: '6f6e76f615fcf6c4a552cce0f51e71c4'
    <<: *facebook_defaults
  GOOGLE:
    <<: *google_defaults
  MANDRILL:
    APIKEY: 'FWDtyP_2VA85dpsXhuudoA'
  WEBSOCKET:
      USE_SSL: 'true'
  RECAPTCHA:
    <<: *recaptcha_defaults
