# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58f007b4fe12ee8a5f85b39f96c284e1660c1f95ae900e84d1499f357b8f53858b606da72758af2a72d982f8339527c3ec0e129b1ec4ff9d52b6d1dea3170ea6

test:
  secret_key_base: ead8a926560a6c881207cf79fd3f544d5a3ec4f58cf740a4053a1f83e0478a939740468de9f71b8473658e89d46261330d33ba22abab0aedc69016d3e17afdc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
